RM := rm -rf
BRIDGE_EXE := studio-mdk-bridge.exe
UV4_EXE := "D:\mdk\UV4\UV4.exe"
UVPROJX_LOC := "C:\Users\1\Desktop\guobang38\stm32f407\project.uvprojx"

.PHONY: mdk_all

mdk_all:
	-$(BRIDGE_EXE) --build --uv4-path $(UV4_EXE) $(UVPROJX_LOC)

mdk_clean:
	-@$(RM) *
	@echo 'success'

